### PR TITLE
Cell Profiler

### PR DESCRIPTION
**Pull request by jburel**
Install the latest version of CellProfiler (v3.1.3) and fix the notebook

Available at https://ome-lochy.openmicroscopy.org/jupyterhub-training/

To test:
* Run the notebook against outreach as trainer-1, Use the dataset  "Cell Profiler Image"
* Make sure that the R notebook still works

To build and test it locally:
* ``docker build -t training-notebooks .``
* ``docker run -it  -p 8888:8888 training-notebooks``

### CODE REVIEW

**Comment by dominikl** [comment]
The R notebook still works, but the CellProfiler notebook doesn't. Running the first cell gives `UnboundLocalError: local variable 'jdk_dir' referenced before assignment` .

**Comment by jburel** [comment]
That is due to the fact that I brought R back ( I removed it at the start)
Ok I know what the problem is

**Comment by dominikl** [comment]
Both notebooks work now. Good to merge 👍

**Comment by joshmoore** [comment]
Didn't get a chance to play with it yet, but certainly looking forward to it. Merging. (Only thing we may want to do in a follow-up is optimize the image size to speed up pull times)

**Comment by jburel** [comment]
When we have a better idea of what we need for training and IDR
some of it will be moved to jupyter-docker this could be a good opportunity to do that

**Pull request merged**
