### PR TITLE
py3 support

### PR DESCRIPTION
**Pull request by jburel**
* use py3 convention and clean up notebook
* Disable CellProfiler. The version does not yet support Python3

To test:
  * Check that the Python and ilastik notebooks work

### CODE REVIEW

**Comment by dominikl** [comment]
Unfortunately I can't build the docker image.
Check this PR's branch out and ran `docker build -t training-notebooks .`
Ended up with:
```
...
Building jupyterlab assets (build:prod:minimize)
An error occured.
RuntimeError: JupyterLab failed to build
```

**Comment by pwalczysko** [comment]
```
Building jupyterlab assets (build:prod:minimize)
An error occured.
RuntimeError: JupyterLab failed to build
See the log file for details:  /tmp/jupyterlab-debug-ysj9mgwp.log
The command '/bin/sh -c conda install -c conda-forge beakerx &&     jupyter labextension install beakerx-jupyterlab' returned a non-zero code: 1
pwalczysko@ls31618~/Work/training-notebooks$ 
```

**Comment by pwalczysko** [comment]
just as @dominikl reported above

**Comment by jburel** [comment]
Which command did you run?

**Comment by pwalczysko** [comment]
``docker build -t training-notebooks .``

**Comment by jburel** [comment]
That's the command that travis is using and it is green :-)

**Comment by pwalczysko** [comment]
@dominikl and me = 2 against travis = 1

**Comment by jburel** [comment]
I ran it locally so it is 2-2 ball in the middle

**Comment by dominikl** [comment]
It's a memory issue. Increase the RAM of the docker vm to 2GB then it works. Nothing to do with the PR.

**Comment by dominikl** [comment]
Tested the python notebooks, everythings works 👍

**Comment by dominikl** [comment]
Ilastik notebook seems to work too. Don't know which dataset/images to use for it. But at least not python related errors. Cellprofiler notebooks don't work `ModuleNotFoundError: No module named 'cellprofiler'` but @pwalczysko suggested that might be expected.

**Comment by jburel** [comment]
@dominikl: it is indicated in the description. CP does not support python3 yet so it is turned off

**Comment by dominikl** [comment]
Actually, ilastik notebook does not work:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-c243fc6e4f96> in <module>
      6 images = conn.getObjects('Image', opts={'dataset': dataset_id})
      7 # Load the model linked to the dataset
----> 8 model_file = load_model(dataset_id, path)
      9 
     10 # Create a new dataset where to upload the generated images

<ipython-input-4-3f84d50a1906> in load_model(dataset_id, path)
     10                 with open(str(file_path), 'w') as f:
     11                     for chunk in ann.getFileInChunks():
---> 12                         f.write(chunk)
     13                 return file_path

TypeError: write() argument must be str, not bytes
```
For step `Save the probabilities as an OMERO image`.
(using https://merge-ci.openmicroscopy.org/web/webclient/?show=dataset-4152 )

Edit: Can be fixed by openinng the file in the `load_model()` method with `'wb'` instead `'w'` @jburel .

**Comment by dominikl** [comment]
Thanks, looks good now. Good to merge 👍

**Comment by jburel** [comment]
Thanks
I will re-activate CP as soon as possible or indicate that the notebook won't work if there is no movement on CP front

**Pull request merged**
