### PR TITLE
Orbit notebook

### PR DESCRIPTION
**Pull request by jburel**
Example on how we could use notebook to replace https://github.com/ome/training-scripts/tree/master/practical/orbit
A large number of examples from https://github.com/mstritt/orbit-image-analysis/tree/master/src/main/groovy/com/actelion/research/orbit/imageAnalysis/scripts
could also be useful

This is to show what is possible 
cc @pwalczysko @jrswedlow

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [TRAINING-merge#151](https://ci.openmicroscopy.org/job/TRAINING-merge/151/). See the [console output](https://ci.openmicroscopy.org/job/TRAINING-merge/151/consoleText) for more details.
Possible conflicts:
  - PR #26 jburel 'Install openCV'
    - Dockerfile
  - PR #27 jburel 'DO NOT MERGE Test dom branch'
    - Dockerfile

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [DOCKER-merge#588](https://ci.openmicroscopy.org/job/DOCKER-merge/588/). See the [console output](https://ci.openmicroscopy.org/job/DOCKER-merge/588/consoleText) for more details.
Possible conflicts:
  - PR #26 jburel 'Install openCV'
    - Dockerfile
  - PR #27 jburel 'DO NOT MERGE Test dom branch'
    - Dockerfile

--conflicts

**Comment by jburel** [comment]
Closing this PR for now.

**Comment by jburel** [comment]
The problem is that the image is now getting very big
@manics is working on a proposal

**Comment by jburel** [comment]
Closing this PR, this will be done in 2 PRs one for orbit one for beakerx

**Pull request closed without merging**
