### PR TITLE
Server name change

### PR DESCRIPTION
**Pull request by jburel**
replace outreach by workshop

cc @pwalczysko

### CODE REVIEW

**Comment by joshmoore** [comment]
Will it be required to periodically flop back and forth?

**Comment by jburel** [comment]
I think I will review the notebook when we have a bit more time and potentially offer a drop down menu

**Comment by pwalczysko** [comment]
Tested via building locally the docker and running the Fiji macro-from-attachment notebook.

Works fine.

**Comment by pwalczysko** [comment]
Failed checks again due to timeout ?

**Review by pwalczysko — APPROVED** [review]
approval conditioned upon answering the travis failure problem

**Comment by jburel** [comment]
Usual timeout issue
I will need to review that when py3 is behind us
Merging before tagging

**Pull request merged**
