### PR TITLE
Update notebook

### PR DESCRIPTION
**Pull request by jburel**
Table is now created using the analysis script
This PR handles new table format

Run the notebook against idr0021 on outreach

To test go to

 * https://ome-lochy.openmicroscopy.org/jupyterhub-internal/hub/login
* Enter your LDAP Credentials
* Select snoopycrimecop/training-notebooks:master_merge_daily
* Click Spawn
* Select the notebook

and

cc @pwalczysko @will-moore

### CODE REVIEW

**Comment by pwalczysko** [comment]
```
Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl, : java.lang.NoSuchMethodException: No suitable method for the given parameters
Traceback:

1. loadDataframe(project, annotationFileID, columns = c(1, 8))
2. loadDataframe(project, annotationFileID, columns = c(1, 8))
3. fac$getTableInfo(ctx, .jlong(id))
4. .jrcall(x, name, ...)
5. .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl, 
 .     .jcast(if (inherits(o, "jobjRef") || inherits(o, "jarrayRef")) o else cl, 
 .         "java/lang/Object"), .jnew("java/lang/String", method), 
 .     j_p, j_pc, use.true.class = TRUE, evalString = simplify, 
 .     evalArray = FALSE)
6. .jcheck(silent = FALSE)

```

This is done on outreach on the "old" table. Note that the table is called ``Summary_from_Fiji``, not the ``batch_roi_export`` -> there is a mismatch there, how do we want to solve this ? (the previous script used to produce ``batch_roi_export`` tables, the present Fiji script produces ``Summary_from_Fiji`` and the name is hardcoded in this playbook

**Comment by pwalczysko** [comment]
```
Error in `$<-.data.frame`(`*tmp*`, "Image", value = character(0)): replacement has 0 rows, data has 405
Traceback:

1. `$<-`(`*tmp*`, "Image", value = character(0))
2. `$<-.data.frame`(`*tmp*`, "Image", value = character(0))
3. stop(sprintf(ngettext(N, "replacement has %d row, data has %d", 
 .     "replacement has %d rows, data has %d"), N, nrows), domain = NA)
```

the table has a different nuber of rows ?

**Comment by will-moore** [comment]
Need to use different table name
```
tableName <- 'Summary_from_Fiji'
```
and to get different columns:
```
# Load the table: column 14, 15 & 16 Dataset, Bounding_Box & Image) directly as R dataframe
df <- loadDataframe(project, annotationFileID, columns=c(14,15,16))
```

**Comment by jburel** [comment]
I am about to push a fix

**Comment by will-moore** [comment]
It works fine for me with those 2 changes

**Comment by pwalczysko** [comment]
This all looks fine here. 

Maybe the only question is:

On the y-axis of the produced plot, there is ``estimated toroid/ring diameter`` - but the numbers in the graph are pure bounding box -> maybe this is intentional, ie. very rough estimate, or is it a remnant of previous naming ?

**Comment by jburel** [comment]
@pwalczysko your comment above is fixed in 20d5404 but that was not included in the version you tested

**Comment by pwalczysko** [comment]
Okay, https://github.com/ome/training-notebooks/commit/20d5404496c638280bb3af0723dcf2baf033bdc6 looks good.

**Pull request merged**
