### PR TITLE
Bump version to 5.4.9

### PR DESCRIPTION
**Pull request by jburel**
Bump version

### CODE REVIEW

**Comment by mtbc** [comment]
Diff looks plausible.

**Comment by manics** [comment]
Docker hub isn't happy: https://hub.docker.com/r/snoopycrimecop/training-notebooks/builds/bq5ujklul64dxxrgkv6rh7a/

**Comment by jburel** [comment]
humm https://anaconda.org/bioconda/python-omero

**Comment by dominikl** [comment]
I still get a
```
ResolvePackageNotFound:
  - python-omero 5.4.9 py27_1
```

**Comment by jburel** [comment]
For some reason it is py27_0 for this version 
https://anaconda.org/bioconda/python-omero/files?version=5.4.9

**Comment by jburel** [comment]
@dominikl The problem should now be fixed

**Comment by joshmoore** [comment]
The index points to which build. i.e. if the code version doesn't change but you update just requirements, then the suffix gets bumped.

**Comment by jburel** [comment]
@joshmoore thanks. Each time we recently ended with 1 so I wrongly assumed a 1 for that version

**Comment by jburel** [comment]
@dominikl, as mentioned in the office, I had to bump the version of r-base otherwise the image cannot be built anymore See https://hub.docker.com/r/snoopycrimecop/training-notebooks/builds/bgyngdcprdjkc3cb6edtv6k/

We cannot yet bump to r-base 3.5, the issue has been closed but the problem still exists, the kernel dies when running any R-notebook

**Comment by jburel** [comment]
https://hub.docker.com/r/snoopycrimecop/training-notebooks/builds/bd3mxzgjj32rflmmz5cbmz/ is green

**Pull request merged**
